# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: 'sam-ray'
  email_provider_password: Furtherwick717
  domain_name: example.com
  mailchimp_api_key: <%= ENV[699b5b63f7294d18f5f132bd912cf3ef-us13] %>
  mailchimp_list_id: <%= ENV[03c86175da] %>
  owner_email: <%= ENV[sam.ray.barton@gmail.com] %>
  secret_key_base: 857714126d5cd76a077fd47c6961d3562ba78761ab7c7bea4635a8ef530e950562e0f0369e9f556ce022be9094c1fb01a303d3357481d49fb311396b8431d1e7

test:
  secret_key_base: 530774e016ca22bcae866d078dad52a12616bf33906af82a0d95da87c5ee157226b3570562064a88b6d862f57210439effbb0af27a3ee4af4513b9e84d7ab5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
